finanzacoffee/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('tasks/createIngreso/', views.createIngreso, name='createIngreso'),
    path('tasks/createGasto/', views.createGasto, name='createGasto'),
    path('actualizar_ingreso/<int:id>/', views.actualizar_ingreso, name='actualizar_ingreso'),
    path('actualizar_gasto/<int:id>/', views.actualizar_gasto, name='actualizar_gasto'),
    path('eliminar_ingreso/<int:id>/', views.eliminar_ingreso, name='eliminar_ingreso'),
    path('eliminar_gasto/<int:id>/', views.eliminar_gasto, name='eliminar_gasto'),
    path('calendario/', views.calendario, name='calendario'),
    path('tarjetas/', views.myTargets, name='tarjetas'),
    path('tarjetas/addTarget/', views.addTarget, name='addTarget'),
    path('cuentasClaras/', views.cuentasClaras, name='cuentasClaras'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TblIngresos(models.Model):
    nombreIngreso = models.TextField(blank=True)
    cantidadIngreso =  models.BigIntegerField(null=False)
    fechaIngreso = models.DateField(null=False)
    tarjeta = models.ForeignKey('TblTarjetas', on_delete=models.SET_NULL, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombreIngreso

class TblGastos(models.Model):
    nombreGasto = models.TextField(blank=True)
    cantidadGasto =  models.BigIntegerField(null=False)
    fechaGasto = models.DateField(null=False)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreGasto

class TblTarjetas(models.Model):
    nombreTarjeta = models.TextField(blank=True)
    numTarjeta =  models.IntegerField(null=True)
    cantidadDisponible =  models.BigIntegerField(null=True)
    tipoTarjeta = models.CharField(max_length=20, choices=(
        ("Credito", "Tarjeta de Crédito"),
        ("Debito", "Tarjeta de Débito"),
        ("Prestamo", "Préstamo"),
        ("Efectivo", "Efectivo"),
    ), null=False)

    fechaPago = models.DateField(null=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreTarjeta

tasks/forms.py
from django.forms import ModelForm
from .models import TblIngresos, TblGastos, TblTarjetas
from django import forms

class CreateIngresosForm(ModelForm):
    class Meta:
        model = TblIngresos
        fields = ['nombreIngreso', 'cantidadIngreso', 'fechaIngreso', 'tarjeta']
        widgets = {
            'nombreIngreso': forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Nombre de tu Ingreso'}),
            'cantidadIngreso': forms.TextInput(attrs={'class': 'form-control', 'type': 'number', 'placeholder': 'Cantidad de tu Ingreso'}),
            'fechaIngreso': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Fecha de tu Ingreso'}),
            'tarjeta': forms.Select(attrs={'class': 'form-control'}),
        }

class CreateGastosForm(ModelForm):
    class Meta:
        model = TblGastos
        fields = ['nombreGasto', 'cantidadGasto', 'fechaGasto']
        widgets = {
            'nombreGasto': forms.TextInput(attrs={'class': 'form-control', 'type': "text", 'placeholder':"Nombre de tu Gasto"}),
            'cantidadGasto': forms.TextInput(attrs={'class': 'form-control', 'type': "number", 'placeholder':"Cantidad de tu Gasto"}),
            'fechaGasto': forms.TextInput(attrs={'class': 'form-control', 'type': "date", 'placeholder':"Fecha de pago"}),
            }

class AddTargetForm(ModelForm):
    class Meta:
        model = TblTarjetas
        fields = ['nombreTarjeta', 'numTarjeta', 'cantidadDisponible', 'tipoTarjeta', 'fechaPago']
        widgets = {
            'nombreTarjeta': forms.TextInput(attrs={'class': 'form-control', 'type': "text", 'placeholder':"Nombre de tu Gasto"}),
            'numTarjeta': forms.TextInput(attrs={'class': 'form-control', 'type': "number", 'placeholder':"Ultimos 4 digitos de la tarjeta"}),
            'cantidadDisponible': forms.HiddenInput(attrs={'value': 0}),
            'tipoTarjeta' : forms.Select(attrs={'class': 'form-control', 'placeholder':"Tipo de Tarjeta"}, choices=(
                ("Credito", "Tarjeta de Crédito"),
                ("Debito", "Tarjeta de Débito"),
                ("Prestamo", "Préstamo"),
                ("Efectivo", "Efectivo"),
            )),
            'fechaPago': forms.TextInput(attrs={'class': 'form-control', 'type': "date", 'placeholder':"Fecha de corte"}),
            }

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.utils.translation import activate
from django.contrib.auth import login, logout, authenticate
from .forms import CreateIngresosForm, CreateGastosForm, AddTargetForm
from .models import TblIngresos, TblGastos, TblTarjetas
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import JsonResponse
import calendar
import json

# Create your views here.


def home(request):
    return render(request, 'home.html')

@login_required
def addTarget(request):
    if request.method == 'GET':
        return render(request, 'addTarget.html', {
            'form': AddTargetForm
        })      
    else:
        try: 
            form = AddTargetForm(request.POST)
            newTarget = form.save(commit=False)
            newTarget.usuario = request.user
            newTarget.save()
            return redirect('tasks')
        except:
            return render(request, 'addTarget.html', {
                'form': AddTargetForm,
                'error': 'Error Add Target'
            })  

@login_required
def calendario(request):
    ingresos = TblIngresos.objects.filter(usuario=request.user)
    gastos = TblGastos.objects.filter(usuario=request.user)

    eventos = []
    for ingreso in ingresos:
        fecha_str = ingreso.fechaIngreso.strftime('%Y-%m-%d')
        eventos.append({
            'title': ingreso.nombreIngreso,
            'date': fecha_str,
            'type': 'Ingreso'
        })
    for gasto in gastos:
        fecha_str = gasto.fechaGasto.strftime('%Y-%m-%d')
        eventos.append({
            'title': gasto.nombreGasto,
            'date': fecha_str,
            'type': 'Gasto'
        })
    eventos = sorted(eventos, key=lambda x: x['date'])
    eventos_json = json.dumps(eventos)

    return render(request, 'calendario.html', {
        'eventos_json': eventos_json
    })

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            # register user
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('tasks')
            except:
                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    'error': 'Username already exists'
                })
        return render(request, 'signup.html', {
            'form': UserCreationForm,
            'error': 'Password do not match'
        })

@login_required
def tasks(request):
    pagoFinal = 0
    ingresos = TblIngresos.objects.filter(usuario=request.user)
    gastos = TblGastos.objects.filter(usuario=request.user)

    datos = []

    # Agregar ingresos a la lista
    for ingreso in ingresos:
        datos.append({
            'id': ingreso.id,
            'nombre': ingreso.nombreIngreso,
            'tipo': 'Ingreso',
            'cantidad': ingreso.cantidadIngreso,
            'fecha': ingreso.fechaIngreso,
        })

    # Agregar gastos a la lista
    for gasto in gastos:
        datos.append({
            'id': gasto.id,
            'nombre': gasto.nombreGasto,
            'tipo': 'Gasto',
            'cantidad': gasto.cantidadGasto,
            'fecha': gasto.fechaGasto,
        })

    datos = sorted(datos, key=lambda x: x['fecha'])
    
    pagos = []
    for dato in datos:
        if dato['tipo'] == 'Ingreso':
            pagoFinal +=  dato['cantidad']
            pagos.append({
                'id': dato['id'],
                'Total': pagoFinal,
                'FechaPago': dato['fecha'],
                'Nombre': dato['nombre'],
                'Cantidad': dato['cantidad'],
                'Tipo': 'Ingreso',
            })    
        else:
            pagoFinal -= dato['cantidad']
            pagos.append({
                'id': dato['id'],
                'Total': pagoFinal,
                'FechaPago': dato['fecha'],
                'Nombre': dato['nombre'],
                'Cantidad': dato['cantidad'],
                'Tipo': 'Gasto',
            })
    return render(request, 'tasks.html', {
        'pagos': pagos
    })

@login_required
def actualizar_ingreso(request, id):
    if request.method == 'GET':
        ingreso = get_object_or_404(TblIngresos, id=id, usuario = request.user)
        form = CreateIngresosForm(instance=ingreso)
        return render(request, 'actualizar_ingreso.html', {'form': form })
    else:
        try:
            ingreso = get_object_or_404(TblIngresos, id=id, usuario = request.user)
            form = CreateIngresosForm(request.POST, instance=ingreso)
            form.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'actualizar_ingreso.html', {'form': form, 'error': "Error updating Ingreso"})

@login_required
def eliminar_ingreso(request, id):
    try:
        ingreso = get_object_or_404(TblIngresos, id=id, usuario = request.user)
        ingreso.delete()
        return redirect('tasks')
    except ValueError:
        return redirect('tasks')

@login_required
def eliminar_gasto(request, id):
    try:
        gasto = get_object_or_404(TblGastos, id=id, usuario = request.user)
        gasto.delete()
        return redirect('tasks')
    except ValueError:
        return redirect('tasks')

@login_required
def actualizar_gasto(request, id):
    if request.method == 'GET':
            gasto = get_object_or_404(TblGastos, id=id)
            form = CreateGastosForm(instance=gasto)
            return render(request, 'actualizar_gasto.html', {'form': form})
    else:
        try:
            gasto = get_object_or_404(TblGastos, id=id, usuario = request.user)
            form = CreateGastosForm(request.POST, instance=gasto)
            form.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'actualizar_gasto.html', {'form': form, 'error': "Error updating Ingreso"})

def signout(request):
    logout(request)
    return redirect('home')

def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None: 
            return render(request, 'signin.html', {
            'form': AuthenticationForm,
            'error': 'Username or Pass is incorrect'
        })
        else:
            login(request, user)
            return redirect('tasks')
        
@login_required
def createIngreso(request):
    if request.method == 'GET':
        tarjetas= TblTarjetas.objects.filter(usuario=request.user) 
        return render(request, 'createIngreso.html', {
            'form': CreateIngresosForm,
            'tarjetas': tarjetas
        })      
    else:
        try:
            form = CreateIngresosForm(request.POST)
            newTask = form.save(commit=False)
            newTask.usuario = request.user
            idTarjeta = form.cleaned_data['tarjeta'].id
            today = timezone.now().date()
            if today >= newTask.fechaIngreso:
                tarjetas = TblTarjetas.objects.filter(usuario=request.user, id = idTarjeta)
                for tarjeta in tarjetas:
                    tarjeta.cantidadDisponible = tarjeta.cantidadDisponible + newTask.cantidadIngreso
                    tarjeta.save()
            newTask.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'createIngreso.html', {
                'form': CreateIngresosForm,
                'error': ValueError
            })  
        
@login_required
def createGasto(request):
    if request.method == 'GET':
        return render(request, 'createGasto.html', {
            'form': CreateGastosForm
        })      
    else:
        try: 
            form = CreateGastosForm(request.POST)
            newTask = form.save(commit=False)
            newTask.usuario = request.user
            newTask.save()
            return redirect('tasks')
        except:
            return render(request, 'createGasto.html', {
                'form': CreateGastosForm,
                'error': 'Plase provide valid data'
            }) 

@login_required     
def myTargets(request):
    activate('es') 
    today = timezone.now().date()
    tarjetas = TblTarjetas.objects.filter(usuario=request.user)
    ingresos = TblIngresos.objects.filter(usuario=request.user, fechaIngreso__lte = today)
    # for ingreso in ingresos:
    #     if ingreso.tarjeta:
    #         tarjetasActualizado = TblTarjetas.objects.filter(usuario=request.user, id = ingreso.tarjeta.id)
    #         for tarjeta in tarjetasActualizado:
    #             tarjeta.cantidadDisponible = tarjeta.cantidadDisponible + ingreso.cantidadIngreso
    #             tarjeta.save()
    for tarjeta in tarjetas:
        if today >= tarjeta.fechaPago:
            tarjeta.fechaPago = tarjeta.fechaPago.replace(
                month=tarjeta.fechaPago.month + 1 if tarjeta.fechaPago.month != 12 else 1,
                year=tarjeta.fechaPago.year + 1 if tarjeta.fechaPago.month == 12 else tarjeta.fechaPago.year,
                day=tarjeta.fechaPago.day
            )
            tarjeta.save()
    return render(request, 'myTargets.html', {
        'tarjetas': tarjetas
    })

@login_required 
def cuentasClaras(request):
    if request.method == 'GET':
        dineroDisponible = 0;

tasks/templates/actualizar_gasto.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow-lg rounded-3" style="background-color: #d2b48c;">
                <div class="card-body p-5">
                    <div class="row">
                        <div class="col-md-6 text-center">
                            <img src="https://static1.squarespace.com/static/63dc43bd20b8ee75ce23df55/t/63e1433978c1693f6438c75e/1675707193281/CC%2BLogo%2BRound.png?format=1500w"
                                class="img-fluid mx-auto d-block">
                        </div>
                        <div class="col-md-6">
                            <h2 class="card-title text-center" style="color: #8b4513;">Editar Gasto</h2>
                            {% if error %}
                            <div class="alert alert-danger" role="alert"
                                style="background-color: #cd853f; color: #fff;">
                                {{ error }}
                            </div>
                            {% endif %}
                            <form method="post" class="needs-validation" novalidate>
                                {% csrf_token %}
                                {{ form.non_field_errors }}

                                <div class="mb-3 form-group">
                                    <label for="nombreGasto" style="color: #8b4513;">Nombre del Gasto:</label>
                                    {{ form.nombreGasto }}
                                    {% if form.nombreGasto.errors %}
                                    <small class="text-danger">{{ form.nombreGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="cantidadGasto" style="color: #8b4513;">Cantidad del Gasto:</label>
                                    {{ form.cantidadGasto }}
                                    {% if form.cantidadGasto.errors %}
                                    <small class="text-danger">{{ form.cantidadGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="fechaGasto" style="color: #8b4513;">Fecha para pagar:</label>
                                    {{ form.fechaGasto }}
                                    {% if form.fechaGasto.errors %}
                                    <small class="text-danger">{{ form.fechaGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <button type="submit" class="btn btn-primary btn-block rounded-pill"
                                    style="background-color: #8b4513; color: #fff;">Guardar Gasto</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/actualizar_ingreso.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow-lg rounded-3" style="background-color: #d2b48c;">
                <div class="card-body p-5">
                    <div class="row">
                        <div class="col-md-6 text-center">
                            <img src="https://static1.squarespace.com/static/63dc43bd20b8ee75ce23df55/t/63e1433978c1693f6438c75e/1675707193281/CC%2BLogo%2BRound.png?format=1500w"
                                class="img-fluid mx-auto d-block">
                        </div>
                        <div class="col-md-6">
                            <h2 class="card-title text-center" style="color: #8b4513;">Editar Ingreso</h2>
                            {% if error %}
                            <div class="alert alert-danger" role="alert"
                                style="background-color: #cd853f; color: #fff;">
                                {{ error }}
                            </div>
                            {% endif %}
                            <form method="post" class="needs-validation" novalidate>
                                {% csrf_token %}
                                {{ form.non_field_errors }}

                                <div class="mb-3 form-group">
                                    <label for="nombreIngreso" style="color: #8b4513;">Nombre del Ingreso:</label>
                                    {{ form.nombreIngreso }}
                                    {% if form.nombreIngreso.errors %}
                                    <small class="text-danger">{{ form.nombreIngreso.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="cantidadIngreso" style="color: #8b4513;">Cantidad del Ingreso:</label>
                                    {{ form.cantidadIngreso }}
                                    {% if form.cantidadIngreso.errors %}
                                    <small class="text-danger">{{ form.cantidadIngreso.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="fechaIngreso" style="color: #8b4513;">Fecha del Ingreso:</label>
                                    {{ form.fechaIngreso }}
                                    {% if form.fechaIngreso.errors %}
                                    <small class="text-danger">{{ form.fechaIngreso.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="tarjeta" style="color: #8b4513;">Tipo de Ingreso:</label>
                                    {{ form.tarjeta }}
                                    {% if form.tarjeta.errors %}
                                    <small class="text-danger">{{ form.tarjeta.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <button type="submit" class="btn btn-primary btn-block rounded-pill"
                                    style="background-color: #8b4513; color: #fff;">Actualizar Ingreso</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/createGasto.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card border-0 shadow-lg rounded-3" style="background-color: #d2b48c;">
                <div class="card-body p-5">
                    <div class="row">
                        <div class="col-md-6 text-center">
                            <img src="https://static1.squarespace.com/static/63dc43bd20b8ee75ce23df55/t/63e1433978c1693f6438c75e/1675707193281/CC%2BLogo%2BRound.png?format=1500w"
                                class="img-fluid mx-auto d-block">
                        </div>
                        <div class="col-md-6">
                            <h2 class="card-title text-center" style="color: #8b4513;">Agregar Gasto</h2>

                            <form action="/tasks/createGasto/" method="post" class="needs-validation" novalidate>
                                {% csrf_token %}
                                {{ form.non_field_errors }}

                                <div class="mb-3 form-group">
                                    <label for="nombreGasto" style="color: #8b4513;">Nombre del Gasto:</label>
                                    <input type="text" class="form-control" id="id_nombreGasto" name="nombreGasto"
                                        placeholder="Nombre de tu Gasto" required>
                                    <!-- {{ form.nombreIngreso }} -->
                                    {% if form.nombreGasto.errors %}
                                    <small class="text-danger">{{ form.nombreGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="cantidadGasto" style="color: #8b4513;">Cantidad del Gasto:</label>
                                    <input type="number" class="form-control" id="id_cantidadGasto"
                                        name="cantidadGasto" placeholder="Cantidad de tu Gasto" required>
                                    <!-- {{ form.cantidadIngreso }} -->
                                    {% if form.cantidadGasto.errors %}
                                    <small class="text-danger">{{ form.cantidadGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <div class="mb-3 form-group">
                                    <label for="fechaGasto" style="color: #8b4513;">Fecha del Gasto:</label>
                                    <input type="date" name="fechaGasto" class="form-control"
                                        pattern="^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$" required/>
                                    {% if form.fechaGasto.errors %}
                                    <small class="text-danger">{{ form.fechaGasto.errors|join:", " }}</small>
                                    {% endif %}
                                </div>

                                <button type="submit" class="btn btn-primary btn-block rounded-pill"
                                    style="background-color: #8b4513; color: #fff;">Guardar Gasto</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/createIngreso.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        margin: 0;
        font-family: 'Arial', sans-serif;
        background-color: #f5f5f5;
    }

    .container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        padding: 20px;
    }

    .no-tarjetas {
        text-align: center;
        background-color: #ffffff;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 20px;
        border-radius: 10px;
        margin: 10px;
    }
</style>

<body>
    {% if tarjetas %}
    <div class="row justify-content-center">
        <div class="card border-0 shadow-lg rounded-3" style="background-color: #d2b48c;">
            <div class="card-body p-5">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <img src="https://static1.squarespace.com/static/63dc43bd20b8ee75ce23df55/t/63e1433978c1693f6438c75e/1675707193281/CC%2BLogo%2BRound.png?format=1500w"
                            class="img-fluid mx-auto d-block">
                    </div>
                    {{ error }}
                    <div class="col-md-6">
                        <h2 class="card-title text-center" style="color: #8b4513;">Agregar Ingreso</h2>

                        <form action="/tasks/createIngreso/" method="post" class="needs-validation" novalidate>
                            {% csrf_token %}
                            {{ form.non_field_errors }}

                            <div class="mb-3 form-group">
                                <label for="nombreIngreso" style="color: #8b4513;">Nombre del Ingreso:</label>
                                <input type="text" class="form-control" id="id_nombreIngreso" name="nombreIngreso"
                                    placeholder="Nombre de tu Ingreso" required>
                                <!-- {{ form.nombreIngreso }} -->
                                {% if form.nombreIngreso.errors %}
                                <small class="text-danger">{{ form.nombreIngreso.errors|join:", " }}</small>
                                {% endif %}
                            </div>

                            <div class="mb-3 form-group">
                                <label for="cantidadIngreso" style="color: #8b4513;">Cantidad del
                                    Ingreso:</label>
                                <input type="number" class="form-control" id="id_cantidadIngreso" name="cantidadIngreso"
                                    placeholder="Cantidad de tu Ingreso" required>
                                <!-- {{ form.cantidadIngreso }} -->
                                {% if form.cantidadIngreso.errors %}
                                <small class="text-danger">{{ form.cantidadIngreso.errors|join:", " }}</small>
                                {% endif %}
                            </div>

                            <div class="mb-3 form-group">
                                <label for="fechaIngreso" style="color: #8b4513;">Fecha del Ingreso:</label>
                                <input type="date" name="fechaIngreso" class="form-control"
                                    pattern="^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$" required />
                                {% if form.fechaIngreso.errors %}
                                <small class="text-danger">{{ form.fechaIngreso.errors|join:", " }}</small>
                                {% endif %}
                            </div>

                            <div class="mb-3 form-group">
                                <label for="tarjeta" style="color: #8b4513;">Tipo de ingreso:</label>
                                {{form.tarjeta}}
                                {% if form.tarjeta.errors %}
                                <small class="text-danger">{{ form.tarjeta.errors|join:", " }}</small>
                                {% endif %}
                            </div>

                            <button type="submit" class="btn btn-primary btn-block rounded-pill"
                                style="background-color: #8b4513; color: #fff;">Guardar Ingreso</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="no-tarjetas">
        <h2>No tienes tarjetas actualmente</h2>
        <p>¡Agrega nuevas tarjetas o efectivo para empezar a gestionar tus finanzas!</p>
        <!-- Puedes agregar aquí algún enlace o botón para agregar tarjetas -->
    </div>
    {% endif %}
</body>

{% endblock %}